PLUGINS = [
    'rbac',
    'manage',
    'insights',
    'orchestration',
    'auth',
    'pricing'
]

UGLY_RBAC = """window.rbac={checkPerm:function(r,e,t,o,n){if(!e)return console.error("checkPerm: no resource type defined"),!1;const s=document.querySelector("mist-app").model;o=o||s&&s.org,n=n||s&&s.user;const i={rename:"edit",tag:"edit_tags",shell:"open_shell"};if(i[r=(r=r||"").replace(/ /g,"_")]&&(r=i[r]),!o)return console.warn("no org found"),!1;if(o.is_owner)return!0;"s"===e.charAt(e.length-1)&&(e=e.slice(0,-1)),console.log("check perm",r,e,t);var a=this,c=[];if(t){var l=!1;if("location"!=e&&"zone"!=e)s[e+"s"]&&s[e+"s"][t]&&(l=s[e+"s"][t].owned_by==n.id);else if("zone"==e){var f;s.zones&&(f=Object.values(s.zones).find((function(r){return r.records&&r.records[t]}))),f&&(l=f.owned_by==n.id)}else if("location"==e){var u;s.clouds&&(u=Object.values(s.clouds).find((function(r){return r.locations&&r.locations[t]}))),u&&(l=u.owned_by==n.id)}if(l)if(o.owner_policy){var p="ALLOW"==o.owner_policy.operator;if(o.owner_policy.rules){var g=o.owner_policy.rules.filter((function(o){return!(o.rtype!=e&&o.rtype||o.action!=r&&o.action||o.rid!=t&&o.rid)}));if(g.length){var d=g[0],h="ALLOW"==d.operator;p=h;if(h){if(Object.keys(d.rtags).length>0){var y={tags:d.rtags};d.constraints&&(y.constraints=d.constraints),p=y}Object.keys(d.constraints).length>0&&(p=d.constraints)}c.push(p)}else c.push(p)}else c.push(p)}else c.push(!0)}if(!c.length)for(var L=Object.values(s.teams).filter((function(r){return a.isMember(n.id,r)})),O=0;O<L.length;O++){var b,A=L[O],m=[];if((m=A.policy.rules).length){if((b=m.filter((function(o){return!(o.rtype!=e&&o.rtype||o.action!=r&&o.action&&""!==r||o.rid!=t&&o.rid&&t)}))).length){if(t){let r={};s[e+"s"]&&s[e+"s"][t].tags&&(r=s[e+"s"][t].tags);for(const e of b){if(!e.rtags||0===Object.keys(e.rtags).length)return"ALLOW"===e.operator;for(const t of Object.keys(e.rtags))if(e.rtags[t]===r[t])return"ALLOW"===e.operator}return"ALLOW"===A.policy.operator}{const r={ids:[],tags:{}},e={ids:[],tags:{}};let t=!0,o=!0;for(let n of b){if(!(n.rid&&""!==n.rid||n.rtags&&0!==Object.keys(n.rtags).length)){if(t&&o)return"ALLOW"===n.operator;if("ALLOW"===n.operator&&o)return!0;if("ALLOW"===n.operator)return e;if("DENY"===n.operator&&t)return!1;if("DENY"===n.operator)return r}n.rid&&("ALLOW"===n.operator&&(r.ids.push(n.rid),t=!1),"DENY"===n.operator&&(e.ids.push(`!${n.rid}`),o=!1)),Object.keys(n.rtags).length>0&&("ALLOW"===n.operator&&(Object.assign(r.tags,n.rtags),t=!1),"DENY"===n.operator&&(Object.keys(n.rtags).forEach((r=>{e.tags[`!${r}`]=n.rtags[r]})),o=!1))}if("ALLOW"===A.policy.operator&&o)return!0;if("ALLOW"===A.policy.operator)return e;if("DENY"===A.policy.operator&&t)return!1;if("DENY"===A.policy.operator)return r}return console.error("checkPerm: Something went wrong!"),!1}c.push("ALLOW"==A.policy.operator)}else c.push("ALLOW"==A.policy.operator)}var v=c.findIndex((function(r){return 0!=r}));return v>-1&&c[v]},isMember:function(r,e){return e.members.indexOf(r)>-1}};"""



