PLUGINS = [
    'rbac',
    'manage',
    'insights',
    'orchestration',
    'auth',
    'pricing'
]
UGLY_RBAC = """window.rbac={checkPerm:function(r,e,t,o,n){const i=document.querySelector("mist-app").model;o=o||i&&i.org,n=n||i&&i.user;const s={rename:"edit",tag:"edit_tags",shell:"open_shell"};if(s[r=r||""]&&(r=s[r]),"s"===e.charAt(e.length-1)&&(e=e.slice(0,-1)),o){if(o.is_owner)return!0;console.log("check perm",r,e,t);var a=this,c=[];if(e&&t){var l=!1;if("location"!=e&&"zone"!=e)i[e+"s"]&&i[e+"s"][t]&&(l=i[e+"s"][t].owned_by==n.id);else if("zone"==e){var f;i.zones&&(f=Object.values(i.zones).find(function(r){return r.records&&r.records[t]})),f&&(l=f.owned_by==n.id)}else if("location"==e){var u;i.clouds&&(u=Object.values(i.clouds).find(function(r){return r.locations&&r.locations[t]})),u&&(l=u.owned_by==n.id)}if(l)if(o.owner_policy){var p="ALLOW"==o.owner_policy.operator;if(o.owner_policy.rules){var g=o.owner_policy.rules.filter(function(o){return!(o.rtype!=e&&o.rtype||o.action!=r&&o.action||o.rid!=t&&o.rid)});if(g.length){var d=g[0],L="ALLOW"==d.operator;p=L;if(L){if(Object.keys(d.rtags).length>0){var h={tags:d.rtags};d.constraints&&(h.constraints=d.constraints),p=h}Object.keys(d.constraints).length>0&&(p=d.constraints)}c.push(p)}else c.push(p)}else c.push(p)}else c.push(!0)}if(!c.length)for(var y=Object.values(i.teams).filter(function(r){return a.isMember(n.id,r)}),O=0;O<y.length;O++){var b,A=y[O],v=[];if((v=A.policy.rules).length){if((b=v.filter(function(o){return!(o.rtype!=e&&o.rtype||o.action!=r&&o.action&&""!==r||o.rid!=t&&o.rid&&t)})).length){if(t){let r={};i[e+"s"]&&i[e+"s"][t].tags&&(r=i[e+"s"][t].tags);for(const e of b){if(!e.rtags||0===Object.keys(e.rtags).length)return"ALLOW"===e.operator;for(const t of Object.keys(e.rtags))if(e.rtags[t]===r[t])return"ALLOW"===e.operator}return"ALLOW"===A.policy.operator}{const r={ids:[],tags:{}},e={ids:[],tags:{}};let t=!0,o=!0;for(let n of b){if(!(n.rid&&""!==n.rid||n.rtags&&0!==Object.keys(n.rtags).length)){if(t&&o)return"ALLOW"===n.operator;if("ALLOW"===n.operator&&o)return!0;if("ALLOW"===n.operator)return e;if("DENY"===n.operator&&t)return!1;if("DENY"===n.operator)return r}n.rid&&("ALLOW"===n.operator&&(r.ids.push(n.rid),t=!1),"DENY"===n.operator&&(e.ids.push(`!${n.rid}`),o=!1)),Object.keys(n.rtags).length>0&&("ALLOW"===n.operator&&(Object.assign(r.tags,n.rtags),t=!1),"DENY"===n.operator&&(Object.keys(n.rtags).forEach(r=>{e.tags[`!${r}`]=n.rtags[r]}),o=!1))}if("ALLOW"===A.policy.operator&&o)return!0;if("ALLOW"===A.policy.operator)return e;if("DENY"===A.policy.operator&&t)return!1;if("DENY"===A.policy.operator)return r}return"Something went wrong!"}c.push("ALLOW"==A.policy.operator)}else c.push("ALLOW"==A.policy.operator)}var W=c.findIndex(function(r){return 0!=r});return W>-1&&c[W]}return console.warn("no org found"),!1},isMember:function(r,e){return e.members.indexOf(r)>-1}};"""


